### ISSUE TITLE
Todo List for getting everything really done.

### ISSUE THREAD

**Issue by lgray** [overline-mining/open-overline-pool#1]
- [x] get open-overline-pool go code compiling
- [x] get bcnode running as a kubernetes service
- [x] rpc shim
- [x] containerize rpc shim
- [x] get ember webserver compiling
- [x] containerize pool webserver
- [x] kubernetes configs for redis
- [ ] kubernetes configs for certificate generation
- [x] kubernetes configs for open-overline-pool
- [x] basic webserver interface tests
- [x] make a testing structure for moving data through the server
- [x] demonstrate I can accurately handle both directions of data flow
- [ ] make bcnode k8s deployment production grade
- [x] make webserver/etc. k8s deployment production grade (runs as user, factorized deployments)
- [x] stratum layer on top of GPU miner
- [x] test stratum GPU miner
- [x] docker setup for stratum GPU miner
- [x] stratum layer on top of CPU miner
- [x] test stratum CPU miner
- [x] docker setup for stratum CPU miner
- [ ] http overline proxy
- [ ] test http proxy
- [x] stratum overline proxy
- [ ] test stratum proxy
- [ ] test deployment + beta testing with real people
- [ ] review results of beta testing, fix bugs, continuous testing
- [ ] production deployments
- [x] open source
